//created on: 08/04/2016
package com.sample.building

//list any import classes here.
import com.sample.domain.building.*;


//declare any global variables here




rule "Your First Rule"

    when
        //conditions
        $room : Room(  )
        $sprinkle : Sprinkler( room == $room )
    then
        //actions
        System.out.println("room: " + $room.getName() + " sprinkler: " + $sprinkle.getRoom().getName());
end

